name: Check for broken links

on:
  push:
    branches: [main, master]
    paths:
      - "src/content/**"
      - "README.md"
      - ".github/workflows/broken-links.yml"
  pull_request:
    branches: [main, master]
    paths:
      - "src/content/**"
      - "README.md"
      - ".github/workflows/broken-links.yml"

permissions:
  contents: read

jobs:
  link-checker:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: Check external content links
        uses: lycheeverse/lychee-action@v1.9.0
        with:
          fail: true
          args: >-
            --user-agent 'curl/7.54'
            --exclude 'https://badam7\.aakashb\.xyz/.*'
            --no-progress
            './src/content/**/*.md'
            './README.md'
